# The Docker image that will be used to build your app.
image: node:lts

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r $(ls | grep -v public) public/
  artifacts:
    paths:
      - public
  only:
    - main
